export const SET_LOADING = "SET_LOADING";
export const SET_COURSE = "SET_COURSE";
export const SET_VIDEOURL = "SET_VIDEOURL";
export const SET_USER_COURSE_LIST = "SET_USER_COURSE_LIST";
export const SET_CURRENT_COURSE_VIEW = "CURRENT_COURSE_VIEW";
